elasticsearch.hosts: [ "${ELASTICSEARCH_HOSTS}" ]
elasticsearch.username: "${ELASTICSEARCH_USERNAME:elastic}"
elasticsearch.password: "${ELASTICSEARCH_PASSWORD:changeme}"
elasticsearch.serviceAccountToken: "${ELASTICSEARCH_SERVICE_TOKEN}"
elasticsearch.ssl.certificateAuthorities: "/etc/ssl/certs/ca-certificates.crt"