server.host: "${SERVER_HOST:0.0.0.0}"
elasticsearch.hosts: ["${ELASTICSEARCH_HOSTS:http://elasticsearch:9200}"]
elasticsearch.username: "${ELASTICSEARCH_USERNAME:elastic}"
elasticsearch.password: "${ELASTICSEARCH_PASSWORD:changeme}"
